#!/usr/bin/env python3
"""Generate the four ranking tables: accuracy and latency, YOLO26 and DEIMv2 separately.

WHY SEPARATE TABLES PER FAMILY. A single merged ranking would imply the two arms rest on the
same evidence, and they do not. Accuracy is fully measured for both -- 30 YOLO26 cells and 8
DEIMv2 variants, all with cross-validation, held-out test and AUC. Latency is not: every
YOLO26 cell has a Core ML measurement, while six of eight DEIMv2 variants have none, for
reasons recorded per row rather than left as blanks.

ACCURACY IS EXACT-IoU THROUGHOUT, never ultralytics' reported mAP -- that scores OBB with
ProbIoU and runs +0.175 optimistic on this dataset, which would put the OBB rows a sixth of a
point too high against everything else in the table.

LATENCY: sustained (15 min) is shown wherever it was measured, because that is the regime an
instrument runs in; burst is shown alongside so the gap is visible. A cold reading always
takes precedence over a preheated one for the same configuration.

    python3 scripts/ranking_tables.py > results/RANKINGS.md
"""
from __future__ import annotations
import glob, json, statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUDGET = 10.0


def load():
    cv = json.loads((ROOT / "results/cv_exact_iou.json").read_text())["per_cell"]
    test = {(r["arch"], r["model"]): r for r in
            json.loads((ROOT / "results/test_set.json").read_text())["results"]}
    pool = {}
    for f in glob.glob(str(ROOT / "results/pooled/*.json")):
        if "summary" in f:
            continue
        d = json.loads(Path(f).read_text())
        pool[(d["arch"], d["model"])] = d
    dby = {}
    for r in json.loads((ROOT / "results/deim_evaluator_check.json").read_text()):
        dby.setdefault(r["model"], []).append(r["exact"])
    dcv = {k: (statistics.mean(v), statistics.stdev(v) if len(v) > 1 else 0.0)
           for k, v in dby.items()}

    burst = {}
    for p in ("latency_m4_640.json", "latency_m4_lowres.json",
              "latency_m4_bigmodels_lowres.json"):
        for r in json.loads((ROOT / "results" / p).read_text())["results"]:
            if r["runtime"] != "coreml":
                continue
            parts = r["weights"].split("-")
            burst[(parts[0], parts[1], r["imgsz"])] = r

    sus = {}
    for f in sorted(glob.glob(str(ROOT / "results/latency_sustained*.json"))):
        for i, r in enumerate(json.loads(Path(f).read_text())["results"]):
            key = r["package"].replace(".mlpackage", "")
            cold = (i == 0)
            prev = sus.get(key)
            if prev and prev["cold"] and not cold:
                continue                       # cold always wins over preheated
            sus[key] = dict(cold=cold, med=r["overall_median_ms"], p95=r["overall_p95_ms"],
                            holds=r["holds_budget_throughout"], breach=r.get("first_breach_at_s"))
    return cv, test, pool, dcv, burst, sus


def main():
    cv, test, pool, dcv, burst, sus = load()
    P = print

    P("# Ranking tables\n")
    P("Accuracy and latency, ranked, with the two architecture families kept separate.")
    P("Generated by `scripts/ranking_tables.py` — regenerate rather than edit by hand.\n")
    P("All accuracy figures are **exact-IoU**, recomputed from the prediction dumps. Ultralytics'")
    P("own mAP scores OBB with ProbIoU and runs **+0.175 optimistic** on this dataset, so its")
    P("numbers are not used anywhere here.\n")
    P("---\n")

    # ---------- 1. YOLO26 accuracy ----------
    P("## 1. YOLO26 — accuracy ranking (30 configurations)\n")
    P("Ranked by 3-fold cross-validation mAP50-95, which is the selection instrument.")
    P("`test` is the 30-annotation held-out set, read once at the end.\n")
    P("| # | configuration | CV mAP50-95 | test mAP50-95 | macro AUC | CV→test gap |")
    P("|---|---|---|---|---|---|")
    rows = sorted(cv.items(), key=lambda kv: -kv[1]["mean"])
    for i, (k, v) in enumerate(rows, 1):
        g, s, z = k.split("-")
        t = test[("yolo26", k)]
        a = pool[("yolo26", k)]["auc"]["macro"]
        gap = t["test_mAP50_95_mean"] - v["mean"]
        name = f"{g}-{s} @ {z}"
        P(f"| {i} | {'**'+name+'**' if i <= 3 else name} | {v['mean']:.4f} ± {v['sd']:.4f} | "
          f"{t['test_mAP50_95_mean']:.4f} ± {t['test_mAP50_95_sd']:.4f} | {a:.4f} | {gap:+.4f} |")
    P()
    P("**Every one of the top twelve is HBB.** Oriented boxes were expected to suit angled")
    P("hands and do not appear until below them — that reversal is a consequence of scoring")
    P("with exact polygon IoU rather than ProbIoU.\n")
    P("**Lower resolution wins.** The best cells are at 416 and 320; every 640 px cell is")
    P("beaten. With 60 training images, 640 px appears to give the model more room to overfit.\n")

    # ---------- 2. DEIMv2 accuracy ----------
    P("---\n")
    P("## 2. DEIMv2 — accuracy ranking (8 variants)\n")
    P("All at 640 px — the architecture is fixed there and cannot be run at another resolution.\n")
    P("| # | variant | backbone | CV mAP50-95 | test mAP50-95 | macro AUC | CV→test gap |")
    P("|---|---|---|---|---|---|---|")
    fam = {"atto": "HGNetv2", "femto": "HGNetv2", "pico": "HGNetv2", "n": "HGNetv2",
           "s": "DINOv3", "m": "DINOv3", "l": "DINOv3", "x": "DINOv3"}
    for i, (v, (m, sd)) in enumerate(sorted(dcv.items(), key=lambda kv: -kv[1][0]), 1):
        t = test[("deimv2", v)]
        a = pool[("deimv2", v)]["auc"]["macro"]
        gap = t["test_mAP50_95_mean"] - m
        nm = f"deimv2-{v}"
        P(f"| {i} | {'**'+nm+'**' if i <= 3 else nm} | {fam[v]} | {m:.4f} ± {sd:.4f} | "
          f"{t['test_mAP50_95_mean']:.4f} ± {t['test_mAP50_95_sd']:.4f} | {a:.4f} | {gap:+.4f} |")
    P()
    P("**A hard capacity floor sits between `pico` and `n`** — a ~9× jump in mAP for roughly")
    P("twice the parameters. atto, femto and pico do not learn the task at all; their AUC is at")
    P("chance and they are excluded from every aggregate in this study.\n")
    P("**Backbone is a confound at the top.** s/m/l/x are DINOv3-pretrained while atto…n are")
    P("HGNetv2, so a DEIMv2 win in the upper rows is *foundation-model pre-training + a DETR")
    P("head*, not architecture alone. The clean architectural comparison against YOLO26 is the")
    P("HGNetv2 line, where `deimv2-n` (0.7922) sits below the best YOLO26 cell (0.8373).\n")

    # ---------- 3. YOLO26 latency ----------
    P("---\n")
    P("## 3. YOLO26 — latency ranking (30 configurations, Core ML on the M4)\n")
    P("Ranked by burst median. **Sustained is the number that matters** for a continuously-")
    P("running instrument; it is measured for six configurations and shown where it exists.\n")
    P("| # | configuration | burst median | burst p95 | jitter | sustained (15 min) | verdict |")
    P("|---|---|---|---|---|---|---|")
    order = sorted(burst.items(), key=lambda kv: kv[1]["median_ms"])
    for i, ((g, s, z), r) in enumerate(order, 1):
        key = f"{g}-{s}_{z}"
        su = sus.get(key)
        if su:
            st = "cold" if su["cold"] else "preheated"
            sus_txt = f"**{su['med']:.2f}** ({st})"
            verdict = ("**holds**" if su["holds"] else f"breach @ {su['breach']:.0f}s")
        else:
            sus_txt = "—"
            verdict = ("*under budget on burst*" if r["median_ms"] <= BUDGET
                       else "over budget on burst")
        P(f"| {i} | {g}-{s} @ {z} | {r['median_ms']:.2f} | {r['p95_ms']:.2f} | "
          f"{r['jitter_ms']:.2f} | {sus_txt} | {verdict} |")
    P()
    P("Rows without a sustained measurement carry a burst verdict only, and that is weaker")
    P("evidence: of the six configurations measured under sustained load, **three that pass on")
    P("burst go on to breach**. Do not read an unmeasured row as deployable.\n")

    # ---------- 4. DEIMv2 latency ----------
    P("---\n")
    P("## 4. DEIMv2 — latency ranking (8 variants)\n")
    P("This table is mostly empty, and the emptiness is a result rather than an omission.\n")
    P("| variant | Core ML export | burst median | sustained (15 min) | verdict |")
    P("|---|---|---|---|---|")
    notes = {
        "n":     ("converts, verified 0.568 px", "4.80", "**14.95** (cold)", "**breach @ 0s**"),
        "s":     ("converts, **output wrong** (259 px)", "—", "—", "not reportable"),
        "m":     ("converts, **output wrong** (260 px)", "—", "—", "not reportable"),
        "l":     ("converts, **output wrong** (213 px)", "—", "—", "not reportable"),
        "x":     ("converts, **output wrong** (277 px)", "—", "—", "not reportable"),
        "atto":  ("not exported", "—", "—", "below capacity floor"),
        "femto": ("not exported", "—", "—", "below capacity floor"),
        "pico":  ("not exported", "—", "—", "below capacity floor"),
    }
    for v in ["n", "s", "m", "l", "x", "atto", "femto", "pico"]:
        e, b, s_, ver = notes[v]
        P(f"| deimv2-{v} | {e} | {b} | {s_} | {ver} |")
    P()
    P("**Only `n` can be timed honestly.** The four DINOv3 variants convert to Core ML *without")
    P("error* and then produce boxes 213–277 px wrong; timing them would report the speed of a")
    P("model that does not work, so the exporter refuses. The three below the capacity floor")
    P("were never exported because they do not learn the task.\n")
    P("**And `n` fails anyway.** Its 4.80 ms burst is the fastest single figure in the study,")
    P("but ~20–30 s of continuous inference takes it to ~15 ms, where it stays — 50% over")
    P("budget, and it cannot trade resolution for speed because it is fixed at 640 px.\n")
    P("So DEIMv2 leads on accuracy and has **no deployable configuration**. YOLO26 is")
    P("recommended for sustained latency and toolchain reliability, not for better accuracy.\n")


if __name__ == "__main__":
    main()
